# label rules used by labelers to match words
# references:
#   - https://github.com/github/issue-labeler


CWL:
  - '(CWL|cwl)'
  - 'workflow'
  
process/wps1:
  - 'WPS-1'
  - 'WPS1'

process/wps1:
  - 'WPS-2'
  - 'WPS2'

process/wps3:
  - 'WPS-3'
  - 'WPS3'
  - 'WPS-REST'
  - 'rest bindings'
  - 'OGC API - Processes'
  - 'OGC-API-Processes'
  
process/workflow:
  - 'workflow'

triage/feature:
  - 'feature'

triage/bug:
  - 'bug'

ci:
  - 'ci'
  - 'travis'
  - 'github'

oas: 
  - '(OpenAPI|openapi)'
  - '(Swagger|swagger)'
  - cornice
  - colander

tests:
  - 'coverage'
  - 'functional test[s]*'
  - 'unittest[s]*'
