# label rules used by labelers to match words
# references:
#   - https://github.com/github/issue-labeler


CWL:
  - '(CWL|cwl)'
  - 'workflow'

feature:
  - 'feature'

bug:
  - 'bug'

ci:
  - 'ci'
  - 'travis'
  - 'github'

oas: 
  - '(OpenAPI|Swagger)'

tests:
  - 'coverage'
  - 'functional test[s]*'
  - 'unittest[s]*'
