# label rules used by PR labelers to match repository files
# references:
#   original: https://github.com/actions/labeler
#   extended: https://github.com/ilyam8/periodic-pr-labeler

# label 'ci' all automation-related steps and files
ci:
  - .*  # all '.<>' files
  - ".github/**"
  - MANIFEST.in
  - hooks/**/*
  - Makefile*
  - Dockerfile*
  - setup.*
  - requirements*
  - tests/travis-ci/**/*

doc:
  - "*.rst"
  # ignore changelog as doc would almost always be tagged
  - "!CHANGES.rst"
  - "*.example"
  - LICENCE*
  - docs/**/*
  - weaver/wps_restapi/api.py
  - weaver/wps_restapi/colander_extras.py
  - weaver/wps_restapi/swagger_definitions.py
  - weaver/wps_restapi/templates/swagger_ui.mako

db:
  - weaver/datatype.py
  - weaver/database/**/*
  - weaver/store/**/*
  - weaver/sort.py

oas: 
  - weaver/wps_restapi/templates/swagger_ui.mako
  - weaver/wps_restapi/colander_extras.py
  - weaver/wps_restapi/swagger_definitions.py

triage/security:
  - weaver/visibility.py

tests:
  - tests/**/*
  - weaver/processes/wps_default.py
  - weaver/processes/wps_testing.py

## -- Files that *always* impact jobs --

job:
  - weaver/execute.py
  - weaver/sort.py
  - weaver/wps_restapi/jobs/**/*
  - weaver/wps_restapi/templates/notification_email_example.mako

## -- WPS processes --

CWL:
  - weaver/processes/wps_process_base.py
  - weaver/processes/wps_package.py
  - weaver/processes/wps_workflow.py

process/builtin:
  - weaver/processes/builtin/**/*
  
process/wps1:
  - weaver/wps.py
  - weaver/processes/wps1*

process/wps2:
  - weaver/wps.py
  - weaver/processes/wps2*

process/wps3:
  - weaver/wps_restapi/**/*
  
process/workflow:
  - weaver/processes/wps_workflow.py
