language: python
# branches:
#  only:
#    - master
os:
  - linux
#  - osx
python:
  - "2.7"
sudo: false
install:
  - make install
  - make start
before_script:
  - sleep 5
script:
#  - make docs
  - make testall
  - make pep8
#after_success:
# - coveralls
matrix:
  allow_failures:
    - os: osx
