language: python
branches:
  only:
    - pingudev
    - develop
    - master
os:
  - linux
python:
  - "2.7"
sudo: false 
install:
  - make install
  - make start
before_script:
  - sleep 5
script:
#  - make docs
  - make testall
#after_success:
# - coveralls
