language: python
branches:
  only:
    - develop
    - master
python:
  - "2.7"
env:
  - DB=mongodb
sudo: false 
services:
  - mongodb
install:
  - make install
before_script:
  - sleep 15
script:
  - make docs
  - make testall
#after_success:
# - coveralls
