name: twitcher
channels:
- defaults
- birdhouse
dependencies:
- python=2.7.12 
- curl 
- pyopenssl
- cryptography
- mako
- pyyaml
# tests
- pytest 
- flake8
- mock
- pbr
- webtest
# ipython
- ipython
# sphinx
- sphinx 
- sphinx_rtd_theme
# twitcher
- argcomplete
- beautiful-soup
- lxml=3.6.0
- paste
- pastedeploy
- requests
- webob
# pywps
- pywps=3.2.6
- gdal
# nginx, supervisor
- nginx=1.10.1
- supervisor=3.3.1
- gunicorn=19.1.0
- gevent=1.1.1
# mongodb
- pymongo=3
- mongodb=2.6.*|3.3.9
- pip:
  - genshi==0.7
  - beaker
  - pyramid-beaker
  - pyramid-rpc
  - sphinx-autoapi==0.4.0
