name: twitcher
channels:
- birdhouse
dependencies:
- argcomplete
- beautiful-soup
- cryptography
- curl
- gdal
- gunicorn
- ipython
- lxml
- mako
- mock
- nginx
- nose
- openssl
- paste
- pastedeploy
- pymongo=3
- pyopenssl
- pytest
- pywps
- pyyaml
- requests
- supervisor
- sphinx
- pip:
  - beaker
  - pyramid-beaker
  - pyramid-rpc
