name: twitcher
channels:
- defaults
- birdhouse
- conda-forge
dependencies:
- python=2.7
- curl
- pyopenssl
- cryptography
- mako
- pyyaml
- icu=56
# tests
- pytest
- flake8
- mock
- pbr
- webtest
# ipython
- ipython
# sphinx
- sphinx
- sphinx_rtd_theme
# twitcher
- argcomplete
- lxml=3.7
- libxslt=1.1.29
- paste
- pastedeploy
- requests
- requests-oauthlib
- webob
# pywps
- pywps=4.0.0
# nginx, supervisor
- nginx=1.10
- supervisor=3.3.1
- gunicorn=19.1.0
- gevent=1.2
# mongodb
- pymongo=3
- mongodb=2.6.*|3.3.9
# magpie
- openssl
- libffi
- libxslt
- libxml2
- zlib
- pip:
  - genshi==0.7
  - pyramid-rpc
  - sphinx-autoapi==0.4.0
  - ziggurat_foundations
  - bcrypt
